const data = [
  {
    name: 'Rima',
    icon: 'https://i.ibb.co/HBR7Mp9/170-w-Fri-Li1.png',
    stars: 1,
    position: 105,
  },
  {
    name: 'Miyako',
    icon: 'https://i.ibb.co/r3D55yD/FNI9UAh.png',
    stars: 2,
    position: 125,
  },
  {
    name: 'Kuka',
    icon: 'https://i.ibb.co/hRVCks0/154-m1qc3-YZ.png',
    stars: 2,
    position: 130,
  },
  {
    name: 'Jun',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_104731.png',
    stars: 3,
    position: 135,
  },
  {
    name: 'Kaori',
    icon: 'https://i.ibb.co/JcnNNTk/071-3n-Ptv-EB.png',
    stars: 2,
    position: 145,
  },
  {
    name: 'Pecorine',
    icon: 'https://i.ibb.co/mDj8HM7/178-9-Igs5x-T.png',
    stars: 1,
    position: 155,
  },
  {
    name: 'Nozomi',
    icon: 'https://i.ibb.co/wMbkXZv/115-e4-DEe-WA.png',
    stars: 3,
    position: 160,
  },
  {
    name: 'Makoto',
    icon: 'https://i.ibb.co/n6FHWjD/150-t-XW1o-QL.png',
    stars: 3,
    position: 165,
  },
  {
    name: 'Akino',
    icon: 'https://i.ibb.co/QrFsmPq/129-Rbt-FJ5h.png',
    stars: 3,
    position: 180,
  },
  {
    name: 'Tsumugi',
    stars: 1,
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_105431.png',
    position: 195,
  },
  {
    name: 'Hiyori',
    icon: 'https://i.ibb.co/ssvpMLw/005-wtvv-Vrt.png',
    stars: 1,
    position: 200,
  },
  {
    name: 'Misogi',
    icon: 'https://i.ibb.co/L1h0cGW/022-Kba-Fb5r.png',
    stars: 1,
    position: 205,
  },
  {
    name: 'Ayane',
    icon: 'https://i.ibb.co/7jLJk3p/Ayane-Icon.jpg',
    stars: 2,
    position: 210,
  },
  {
    name: 'Tamaki',
    icon: 'https://i.ibb.co/rkWMG4C/156-4qq-UTe-A.png',
    stars: 2,
    position: 215,
  },
  {
    name: 'Eriko',
    icon: 'https://i.ibb.co/BqHPqj4/103-u-Bp9qxm.png',
    stars: 2,
    position: 230,
  },
  {
    name: 'Pecorine (Summer)',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_107531.png',
    stars: 1,
    position: 235,
  },
  {
    name: 'Kurumi',
    icon: 'https://i.ibb.co/RPz95D4/084-x0-Onhf-X.png',
    stars: 1,
    position: 240,
  },
  {
    name: 'Djeeta',
    icon: 'https://i.ibb.co/k9X6XyY/176-la8dqwk.png',
    stars: 3,
    position: 245,
  },
  {
    name: 'Rei',
    icon: 'https://i.ibb.co/Yb3Dt8w/017-6-Bqi112.png',
    stars: 1,
    position: 250,
  },
  {
    name: 'Shizuru',
    icon: 'https://i.ibb.co/dJ0nvHn/161-4h4-R8-GA.png',
    stars: 3,
    position: 285,
  },
  {
    name: 'Mimi',
    icon: 'https://i.ibb.co/VB4396T/079-x-WM3o-Pg.png',
    stars: 2,
    position: 360,
  },
  {
    name: 'Shinobu',
    icon: 'https://i.ibb.co/dbJ5Kkh/124-jyi-E5-Xb.png',
    stars: 2,
    position: 365,
  },
  {
    name: 'Mahiru',
    icon: 'https://i.ibb.co/gW0KNLt/134-46-WVy-Bq.png',
    stars: 2,
    position: 395,
  },
  {
    name: 'Yukari',
    icon: 'https://i.ibb.co/26nRPwT/137-xb4e20-F.png',
    stars: 1,
    position: 405,
  },
  {
    name: 'Monika',
    icon: 'https://i.ibb.co/cFdTpn6/172-z-G1-IEk-N.png',
    stars: 3,
    position: 410,
  },
  {
    name: 'Ninon',
    icon: 'https://i.ibb.co/KX3qc8D/119-j-Lc-Tib-Q.png',
    stars: 3,
    position: 415,
  },
  {
    name: 'Mifuyu',
    icon: 'https://i.ibb.co/ykTRFvC/159-kwcxufe.png',
    stars: 2,
    position: 420,
  },
  {
    name: 'Illya',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_104431.png',
    stars: 1,
    position: 425,
  },
  {
    name: 'Saren',
    icon: 'https://i.ibb.co/9hn7GrJ/109-9r-Dku-Ug.png',
    stars: 3,
    position: 430,
  },
  {
    name: 'Anna',
    icon: 'https://i.ibb.co/RpbGThP/041-e-Lt-E7-GS.png',
    stars: 3,
    position: 440,
  },
  {
    name: 'Kokkoro',
    icon: 'https://i.ibb.co/rw6WJL0/180-Zc-YCr2h.png',
    stars: 1,
    position: 500,
  },
  {
    name: 'Kokkoro (Summer)',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_107631.png',
    stars: 1,
    position: 535,
  },
  {
    name: 'Rin',
    icon: 'https://i.ibb.co/FxXVjbR/099-J1-BVpy-U.png',
    stars: 2,
    position: 550,
  },
  {
    name: 'Mitsuki',
    icon: 'https://i.ibb.co/dQs5JPf/165-h-GY5igu.png',
    stars: 2,
    position: 560,
  },
  {
    name: 'Akari',
    icon: 'https://i.ibb.co/qpW9Cy4/027-43c-Ap-Ej.png',
    stars: 2,
    position: 570,
  },
  {
    name: 'Yori',
    icon: 'https://i.ibb.co/Z1G2wgP/088-r-LW0-T2r.png',
    stars: 1,
    position: 575,
  },
  {
    name: 'Arisa',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_106331.png',
    stars: 3,
    position: 625,
  },
  {
    name: 'Rino',
    icon: 'https://i.ibb.co/w7N5Ltq/050-Wa-Bh9-AQ.png',
    stars: 3,
    position: 700,
  },
  {
    name: 'Suzuna',
    icon: 'https://i.ibb.co/R3czvQk/067-j-ZWl-GNw.png',
    stars: 2,
    position: 705,
  },
  {
    name: 'Shiori',
    icon: 'https://i.ibb.co/8NLRMb6/143-Xu9-QCv-H.png',
    stars: 2,
    position: 710,
  },
  {
    name: 'Io',
    icon: 'https://i.ibb.co/FxP311L/076-k-J5z-G3-J.png',
    stars: 3,
    position: 715,
  },
  {
    name: 'Suzume',
    icon: 'https://i.ibb.co/zXdjy4x/096-GPp9-Hm5.png',
    stars: 1,
    position: 720,
  },
  {
    name: 'Misato',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_101531.png',
    stars: 1,
    position: 735,
  },
  {
    name: 'Karyl',
    icon: 'https://i.ibb.co/KGvKc8b/182-Jrj-Wn-Sz.png',
    stars: 1,
    position: 750,
  },
  {
    name: 'Hatsune',
    icon: 'https://i.ibb.co/dg0s9tH/054-Yv-BLASY.png',
    stars: 3,
    position: 755,
  },
  {
    name: 'Misaki',
    icon: 'https://i.ibb.co/6bbNPm8/163-t-RK7j-Kb.png',
    stars: 1,
    position: 760,
  },
  {
    name: 'Aoi',
    icon: 'https://i.ibb.co/vmtJGRZ/145-ALwm-A00.png',
    stars: 1,
    position: 785,
  },
  {
    name: 'Chika',
    icon: 'https://i.ibb.co/fpvqSCr/148-eh0v-VC8.png',
    stars: 2,
    position: 790,
  },
  {
    name: 'Maho',
    icon: 'https://i.ibb.co/9yvpRcs/044-r7-LWef-P.png',
    stars: 3,
    position: 795,
  },
  {
    name: 'Yui',
    icon: 'https://i.ibb.co/x3vjvNq/010-P0-Ea6ph.png',
    stars: 1,
    position: 800,
  },
  {
    name: 'Yuki',
    icon: 'https://i.ibb.co/Scq9hQz/AEbSSVy.png',
    stars: 2,
    position: 805,
  },
  {
    name: 'Kyoka',
    icon: 'https://pricalc.b-cdn.net/en/unit/extract/latest/icon_unit_103631.png',
    stars: 2,
    position: 810,
  },
];

export default data;
